### ISSUE TITLE
Pub sub with NATS

### ISSUE THREAD

**Issue by gedw99** [livefir/fir#40]
I use nats with htmx.

fir could too .

then all endpoints are virtualised and so are the handlers.

**Comment by gedw99** [comment]
nats can be embedded also, so can make it easier for deployment

**Comment by adnaan** [comment]
Hi @gedw99 . Generally looks like an interesting idea but right now focused on getting the event -> template change api right. Next up is https://github.com/livefir/fir/issues/42

**Comment by adnaan** [comment]
Unsure how NATS fits into Fir. I ran some benchmarks and the combination of Redis + Websocket is good enough for now. Will revisit this when scale becomes a problem.
